### ISSUE TITLE
Requests

### ISSUE THREAD

**Issue by BasicHumanUnit** [dunklesToast/XMRigFrontend#4]
Hey, thanks for setting this up. Two things/thoughts.

 

- Had some issues getting the url's right, maybe add an example above the URL entry like - (Ex: http://hostname)

- Any way to add an overview page to show all the added hosts with some info from each?

**Comment by dunklesToast** [comment]
Hey!
Could you please clarify what your problems were with the URL?
Overview Page sounds nice - will add it in a next release :)

**Comment by BasicHumanUnit** [comment]
Awesome. Thank you.
As for the URL I eventually figured it out but I see people with less knowledge having issue. This is where im talking-

![image](https://user-images.githubusercontent.com/31963086/34726661-b6bfbea6-f522-11e7-8dc6-8a5d8936ee16.png)

**Comment by dunklesToast** [comment]
I fixed the README now. Should be more clear now. The Overview is quite difficult because I need to send a request to every Miner 🤔 Maybe you can use the Proxy and add this (and the single miners).
But I'll try to implement that soon - or if you want to you can also do this and create a Pull Request!
